name: ~change log level

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: environment to deploy to
        required: true
      should_run_test:
        type: string
        description: should run test
        required: true

jobs:
  log-level:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.2'
          channel: 'stable'

      - name: Set up java
        uses: actions/setup-java@v2
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Get Dependencies
        run: flutter pub get

      - name: Run test
        if: ${{ inputs.should_run_test }}
        run: flutter test

      - name: Build APK
        run: flutter build apk --release